FROM plot2do_dependencies

# Contexto: Copia todo el contenido de este directerio adentro del container en la carpeta /app
COPY ./dh_plot2do /home/rstudio/plot2DO

WORKDIR /home/rstudio/plot2DO

# Cuando el container se lance va a ejecutar este comando
# CMD ["echo", "hola"]

